CREATE TABLE PRODUCT_DETAILS(
  ID BIGINT(20) NOT NULL PRIMARY KEY,
  NAME VARCHAR(200) NOT NULL,
  CATAGORY_ID BIGINT(20) NOT NULL,
  SUB_CATAGORY_ID BIGINT(20) NOT NULL,
  MATERIALTYPE_ID BIGINT(20) NOT NULL,
  BARCODE BIGINT(20) NOT NULL,
  VENDOR_ID BIGINT(20) NOT NULL,
  COLOR VARCHAR(200),
  SIZE VARCHAR(200),
  PRICE_ID BIGINT(20) NOT NULL,
  QUANTITY_ID BIGINT(20) NOT NULL,
   DOCUMENT_ID BIGINT(20) NOT NULL,
  DESCRIPTION_ID BIGINT(20) NOT NULL
);



CREATE TABLE PROD_DESC_DETAILS (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  PRODUCT_ID BIGINT(20)  NOT NULL,
  DESC_TEXT VARCHAR(200),
  CAPTION VARCHAR(100),
  TAG_NUMBER BIGINT(20) NOT NULL,
  DESIGN_DESC VARCHAR(200),
  TECHNICAL_SPEC VARCHAR(200),
   FOREIGN KEY (PRODUCT_ID)  REFERENCES PRODUCT_DETAILS(ID)
  );

 CREATE TABLE CATAGORY_DETAILS(
  ID BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(200) NOT NULL,
  DISPLAYNAME VARCHAR(200)  NOT NULL
); 


CREATE TABLE PROD_DOCUMENT_DETAILS(
  ID BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  PRODUCT_ID BIGINT(20) NOT NULL,
  IMAGE VARCHAR(200) NOT NULL,
  RIGHT_IMAGE VARCHAR(200),
  FRONT_IMAGE VARCHAR(200),
  BACK_IMAGE VARCHAR(200),
  LEFT_IMAGE VARCHAR(200),
  OTHER_IMAGE VARCHAR(200),
  FOREIGN KEY (PRODUCT_ID)  REFERENCES PRODUCT_DETAILS(ID)
);


CREATE TABLE PRICE_DETAILS(
  ID BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  PRODUCT_ID BIGINT(20) NOT NULL,
  SELL_PRICE DECIMAL(10,2),
  VENDOR_PRICE DECIMAL(10) NOT NULL,
  MRP_PRICE DECIMAL(10,2),
  HM_TAG_PRICE DECIMAL(10,2),
  MAKING_PRICE DECIMAL(10,2),
  FOREIGN KEY (PRODUCT_ID)  REFERENCES PRODUCT_DETAILS(ID)
); 




CREATE TABLE QUANTITY_DETAILS(
  ID BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  PRODUCT_ID BIGINT(20) NOT NULL,
  TYPE      VARCHAR(10),
  NET_WT  DECIMAL(10,2),
  GROSS_WT DECIMAL(10,2),
  MEENA_WT DECIMAL(10,2),
  WASTAGE BIGINT(10),
  PURE_WT DECIMAL(10,2),
  STONE_ID BIGINT(20),
  FOREIGN KEY (PRODUCT_ID)  REFERENCES PRODUCT_DETAILS(ID)
) 




CREATE TABLE QUANTITY_DETAILS(
  ID BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  PRODUCT_ID BIGINT(20) NOT NULL,
  PRODUCT_QUANTITY_TYPE      VARCHAR(10),
  PRODUCT_UNIT_TYPE VARCHAR(10),
  NET_WT  DECIMAL(10,2),
  GROSS_WT DECIMAL(10,2),
  MEENA_WT DECIMAL(10,2),
  WASTAGE BIGINT(10),
  PURE_WT DECIMAL(10,2),
  STONE_ID BIGINT(20),
  FOREIGN KEY (PRODUCT_ID)  REFERENCES PRODUCT_DETAILS(ID)
) 



CREATE TABLE STONE_DETAILS(
  ID BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  QUANTITY_ID BIGINT(20) NOT NULL,
  STONE_TYPE varchar(100) ,
  STONE_WT DECIMAL(10,2),
  STONE_COLOR varchar(100) ,
  STONE_PCS BIGINT(20),
  STONE_PRICE DECIMAL(10,2),
  FOREIGN KEY (QUANTITY_ID)  REFERENCES QUANTITY_DETAILS(ID)
);



CREATE TABLE SUB_CATAGORY(
   ID BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
   CATAGORY_ID BIGINT(20) NOT NULL,
   NAME VARCHAR(200) NOT NULL,
   DISPLAY_NAME VARCHAR(200) NOT NULL,
   FOREIGN KEY(CATAGORY_ID) REFERENCES CATAGORY_DETAILS(ID)
);

